import {
  createAppleSplashScreens,
  defineConfig,
  minimal2023Preset,
} from '@vite-pwa/assets-generator/config';

export default defineConfig({
  headLinkOptions: {
    preset: '2023',
  },
  images: 'public/favicon.svg',
  preset: {
    ...minimal2023Preset,
    appleSplashScreens: createAppleSplashScreens(
      {
        darkResizeOptions: { background: 'black', fit: 'contain' },
        linkMediaOptions: { addMediaScreen: true, basePath: '/', log: true, xhtml: true },
        name: (landscape, size, dark) => {
          return `apple-splash-${landscape ? 'landscape' : 'portrait'}-${typeof dark === 'boolean' ? (dark ? 'dark-' : 'light-') : ''}${size.width}x${size.height}.png`;
        },
        padding: 0.3,
        png: {
          compressionLevel: 6,
          quality: 100,
        },
        resizeOptions: { background: 'white', fit: 'contain' },
      },
      [
        'iPad Pro 12.9"',
        'iPad Pro 11"',
        'iPad Pro 10.5"',
        'iPad Pro 9.7"',
        'iPad mini 7.9"',
        'iPad Air 10.5"',
        'iPad Air 9.7"',
        'iPad 10.2"',
        'iPad 9.7"',
        'iPhone 14 Pro Max',
        'iPhone 14 Pro',
        'iPhone 14 Plus',
        'iPhone 14',
        'iPhone 13 Pro Max',
        'iPhone 13 Pro',
        'iPhone 13',
        'iPhone 13 mini',
        'iPhone 12 Pro Max',
        'iPhone 12 Pro',
        'iPhone 12',
        'iPhone 12 mini',
        'iPhone 11 Pro Max',
        'iPhone 11 Pro',
        'iPhone 11',
        'iPhone XS Max',
        'iPhone XS',
        'iPhone XR',
        'iPhone X',
        'iPhone 8 Plus',
        'iPhone 8',
        'iPhone 7 Plus',
        'iPhone 7',
        'iPhone 6s Plus',
        'iPhone 6s',
        'iPhone 6 Plus',
        'iPhone 6',
        'iPhone SE 4.7"',
        'iPhone SE 4"',
        'iPod touch 5th generation and later',
      ],
    ),
  },
});
